# SETUP
title: Recherchequellen
description: Kuratierte Auswahl hilfreicher Recherchequellen
tagline: Kuratierte Quellen für Blogger, Journalisten und Autoren.

# PATH
github: 'https://github.com/nihilor/recherchequellen'
baseurl: '/recherchequellen'
url: 'https://nihilor.github.io/recherchequellen'
footer: 'Designed, built, and maintained by <a href="http://twitter.com/marklubkowitz">@marklubkowitz</a>. Based upon Kurator, a jekyll theme, by <a href="http://twitter.com/marklubkowitz">@marklubkowitz</a>.<br>Code licensed under <a href="https://github.com/nihilor/steamgamer/blob/master/LICENSE">MIT</a>. Content licensed under <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>'

# GOOGLE ANALYTICS
googleanalytics: 

# PROFILES
profiles:
    - name: Twitter
      icon: fa-twitter
      link: http://twitter.com/marklubkowitz
    - name: Facebook
      icon: fa-facebook 
      link: https://www.facebook.com/Mark-Lubkowitz-1624537281099925/
    - name: RSS
      icon: fa-rss 
      link: http://nihilor.github.io/recherchequellen/feed.xml
    - name: Github
      icon: fa-github 
      link: https://github.com/nihilor/recherchequellen
        

# OPENGRAPH
opengraph:
    locale: en_US
    type: website
    title: Recherchequellen - Kuratierte Auswahl hilfreicher Recherchequellen
    description: Kuratierte Quellen für Blogger, Journalisten und Autoren.
    url: 'http://nihilor.github.io/research'
    site_name: Recherchequellen
    image:

# ABOUT
author:
    name: Mark Lubkowitz
    url: https://mlu.io
    
# CALL TO ACTION
cta:
    title: 
    text: 
    link: 
    linktext: 

# Gems
gems:
    - jekyll-paginate

# Collection
collections:
    curation:
        output: true

# Others
markdown: kramdown
kramdown:
    auto_ids: true
sass:
    sass_dir: css
    style: compressed
exclude:
- README.md
safe: true
lsi: false